### ISSUE TITLE
argument -tL: invalid <lambda> value error on specifying local file

### ISSUE THREAD

**Issue by bugbaba** [vortexau/dnsvalidator#15]
Hi vortex,

I have been trying `dnsvalidator` and while it seems to be running well with the `-tL` argument value as url but when I am passing a local file path it is giving this error:

![image](https://user-images.githubusercontent.com/29960776/63950018-e1952b00-ca98-11e9-891d-12b4bb685975.png)

Can you please look into this and correct me if I am doing something wrong.

Thanks :)

**Comment by vortexau** [comment]
Confirmed. Thanks for the submission.

**Comment by vortexau** [comment]
Exclusion List `-eL` is similarly affected:

```
$ docker run -v $(pwd):/dnsvalidator/output -t dnsvalidator -eL /dnsvalidator/output/resolvers.txt -threads 10 -o /dnsvalidator/output/resolvers.txt
usage: dnsvalidator [-h] [-t TARGET | -tL TARGET_LIST]
                    [-e EXCLUSION | -eL EXCLUSIONS_LIST] [-o OUTPUT]
                    [-r ROOTDOMAIN] [-q QUERY] [-threads THREADS]
                    [-timeout TIMEOUT] [--no-color] [-v | --silent]
dnsvalidator: error: argument -eL: invalid <lambda> value: '/dnsvalidator/output/resolvers.txt'
```

**Comment by jburger** [comment]
:wave: OK if I drop a PR on this one? I'm no python expert but I reckon I got something working

**Comment by vortexau** [comment]
Absolutely!

**Comment by jburger** [comment]
Thanks - let me know how it goes for you!

https://github.com/vortexau/dnsvalidator/pull/19

**Comment by Smismi11** [comment]
Any updates on this?

**Comment by chppppp** [comment]
any work around?

**Comment by vortexau** [comment]
Merged PR which resolves this issue.

**Comment by jburger** [comment]
Thanks @vortexau !
